/**
 * 收录时间回填脚本（生成 src/data/added-at.generated.ts）
 *
 * 收录日期按以下优先级确定：
 *   1. `data/sites/*.json` 中该 iconId 首次出现的提交日期（人工收录）
 *   2. `src/data/icons.generated.ts` 中该 id 首次出现的提交日期（随同步进入）
 *   3. 尚未提交的新同步条目 → `ICON_SYNCED_AT`（最近一次图标同步时间）
 *   4. 兜底：仓库首个提交日期，仍缺失则取今天
 *
 * 生成文件已入库，脚本可重复执行且结果稳定（相同 git 历史 → 相同输出）。
 *
 * 用法：
 *   pnpm backfill:added-at            # 写入生成文件
 *   pnpm backfill:added-at --check    # 只检查差异，不写文件（CI 用）
 */
import { execFileSync } from 'node:child_process';
import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

import { ICON_META, ICON_SYNCED_AT } from '../src/data/icons.generated';
import { logger } from './utils/log';

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const OUTPUT = resolve(ROOT, 'src/data/added-at.generated.ts');
const ICONS_FILE = 'src/data/icons.generated.ts';
const SITES_DIR = 'data/sites';

const ICON_ID_PATTERN = /^\s*id:\s*['"]([^'"]+)['"],$/gm;
const OVERRIDE_ID_PATTERN = /^\+\s*"iconId"\s*:\s*"([^"]+)"/gm;

function git(args: string[]): string | null {
  try {
    return execFileSync('git', args, { cwd: ROOT, encoding: 'utf8', maxBuffer: 32 * 1024 * 1024 });
  } catch {
    return null;
  }
}

function toDay(iso: string | null | undefined): string | null {
  if (!iso) return null;
  const match = /^\d{4}-\d{2}-\d{2}/.exec(iso.trim());
  return match ? match[0] : null;
}

/** 涉及图标元数据或站点数据的提交（按时间正序） */
function listCommits(): { sha: string; day: string }[] {
  const raw = git(['log', '--format=%H %aI', '--reverse', '--', ICONS_FILE, SITES_DIR]);
  if (!raw) return [];
  return raw
    .split('\n')
    .map((line) => line.trim())
    .filter(Boolean)
    .map((line) => {
      const [sha, iso] = line.split(' ');
      return { sha, day: toDay(iso) ?? '' };
    })
    .filter((commit) => commit.sha && commit.day);
}

function collectFromCommits(commits: { sha: string; day: string }[]): Map<string, string> {
  const firstSeen = new Map<string, string>();

  for (const { sha, day } of commits) {
    const iconsContent = git(['show', `${sha}:${ICONS_FILE}`]);
    if (iconsContent) {
      for (const match of iconsContent.matchAll(ICON_ID_PATTERN)) {
        if (!firstSeen.has(match[1])) firstSeen.set(match[1], day);
      }
    }

    const sitesDiff = git(['show', sha, '--', SITES_DIR]);
    if (sitesDiff) {
      for (const match of sitesDiff.matchAll(OVERRIDE_ID_PATTERN)) {
        if (!firstSeen.has(match[1])) firstSeen.set(match[1], day);
      }
    }
  }

  return firstSeen;
}

function resolveFallbackDay(): string {
  const syncDay = toDay(ICON_SYNCED_AT);
  if (syncDay) return syncDay;

  const firstCommit = git(['log', '--reverse', '--format=%aI']);
  const firstDay = toDay(firstCommit?.split('\n')[0]);
  if (firstDay) return firstDay;

  return new Date().toISOString().slice(0, 10);
}

function renderFile(addedAt: Record<string, string>, fallbackDay: string): string {
  const body = Object.entries(addedAt)
    .map(([iconId, day]) => `  ${JSON.stringify(iconId)}: ${JSON.stringify(day)},`)
    .join('\n');

  // 不写入生成时间：保证相同 git 历史产生完全相同的输出，`--check` 才有意义
  return `// @generated by scripts/backfill-added-at.ts — DO NOT EDIT
// 条目数量：${Object.keys(addedAt).length}

export const ADDED_AT_SOURCE = 'git-history';

/** 回填兜底日期（未纳入 git 历史的新同步条目） */
export const ADDED_AT_FALLBACK = ${JSON.stringify(fallbackDay)};

/** iconId → 收录日期（YYYY-MM-DD） */
export const ADDED_AT: Record<string, string> = {
${body}
};
`;
}

function main() {
  const args = process.argv.slice(2);
  const checkOnly = args.includes('--check');

  const commits = listCommits();
  if (commits.length === 0) {
    logger.warn('未读取到 git 历史（非 git 仓库或尚无提交），全部条目将使用兜底日期');
  }

  const firstSeen = collectFromCommits(commits);
  const fallbackDay = resolveFallbackDay();

  const addedAt: Record<string, string> = {};
  let backfilled = 0;
  let fallbackCount = 0;

  for (const meta of [...ICON_META].sort((a, b) => a.id.localeCompare(b.id))) {
    const day = firstSeen.get(meta.id) ?? fallbackDay;
    if (firstSeen.has(meta.id)) backfilled += 1;
    else fallbackCount += 1;
    addedAt[meta.id] = day;
  }

  const content = renderFile(addedAt, fallbackDay);

  if (checkOnly) {
    let previous = '';
    try {
      previous = readFileSync(OUTPUT, 'utf8');
    } catch {
      logger.error('生成文件不存在，请先执行 pnpm backfill:added-at');
      process.exit(1);
    }
    if (previous.trim() === content.trim()) {
      logger.success('收录时间映射与 git 历史一致，无需更新');
      return;
    }
    logger.error('收录时间映射已过期，请执行 pnpm backfill:added-at 后提交');
    process.exit(1);
  }

  writeFileSync(OUTPUT, content, 'utf8');

  logger.summary(`已写入 ${OUTPUT.replace(ROOT, '.')}`, {
    条目总数: ICON_META.length,
    按历史回填: backfilled,
    使用兜底日期: fallbackCount,
    兜底日期: fallbackDay,
  });
}

main();
