/**
 * 贡献者统计脚本（生成 src/data/contributors.generated.ts）
 *
 * 从 git 历史聚合贡献者：提交数、首次/最近提交日期、涉及 data/ 目录的提交数。
 * 隐私：只输出用户名（按邮箱聚合去重），不写入邮箱。
 *
 * 幂等：输出不含生成时间，相同 git 历史产生完全一致的产物，便于 `--check` 校验。
 *
 * 用法：
 *   pnpm build:contributors            # 写入生成文件
 *   pnpm build:contributors --check    # 只校验是否与 git 历史一致
 */
import { execFileSync } from 'node:child_process';
import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

import { logger } from './utils/log';

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const OUTPUT = resolve(ROOT, 'src/data/contributors.generated.ts');
const COMMIT_MARKER = '__C__';

interface Contributor {
  /** 展示用户名（取提交者姓名） */
  name: string;
  commits: number;
  /** 涉及 data/ 目录的提交数 */
  dataCommits: number;
  firstCommit: string;
  lastCommit: string;
}

interface Accumulator extends Contributor {
  email: string;
}

function git(args: string[]): string | null {
  try {
    return execFileSync('git', args, { cwd: ROOT, encoding: 'utf8', maxBuffer: 64 * 1024 * 1024 });
  } catch {
    return null;
  }
}

function toDay(iso: string): string {
  return iso.slice(0, 10);
}

/** 解析 `git log --pretty=format:__C__... --name-only` 的输出 */
function collect(): Contributor[] {
  const raw = git(['log', '--pretty=format:__C__%an|%ae|%aI', '--name-only']);
  if (!raw) {
    logger.warn('未读取到 git 历史（非 git 仓库或尚无提交），贡献者列表将为空');
    return [];
  }

  const map = new Map<string, Accumulator>();
  let current: Accumulator | null = null;
  let touchedData = false;

  const flush = () => {
    if (current && touchedData) current.dataCommits += 1;
    touchedData = false;
  };

  for (const line of raw.split('\n')) {
    const text = line.trim();
    if (text.startsWith(COMMIT_MARKER)) {
      flush();
      const [name, email, iso] = text.slice(COMMIT_MARKER.length).split('|');
      if (!name || !email || !iso) {
        current = null;
        continue;
      }
      const day = toDay(iso);
      const key = email.toLowerCase();
      const existing = map.get(key);
      if (existing) {
        existing.commits += 1;
        existing.firstCommit = existing.firstCommit < day ? existing.firstCommit : day;
        existing.lastCommit = existing.lastCommit > day ? existing.lastCommit : day;
        current = existing;
      } else {
        current = {
          name,
          email: key,
          commits: 1,
          dataCommits: 0,
          firstCommit: day,
          lastCommit: day,
        };
        map.set(key, current);
      }
      continue;
    }

    if (text.startsWith('data/')) touchedData = true;
  }
  flush();

  return [...map.values()]
    .map(({ name, commits, dataCommits, firstCommit, lastCommit }) => ({
      name,
      commits,
      dataCommits,
      firstCommit,
      lastCommit,
    }))
    .sort((a, b) => b.commits - a.commits || a.name.localeCompare(b.name));
}

function render(contributors: Contributor[]): string {
  const body = contributors
    .map((item) =>
      [
        '  {',
        `    name: ${JSON.stringify(item.name)},`,
        `    commits: ${item.commits},`,
        `    dataCommits: ${item.dataCommits},`,
        `    firstCommit: ${JSON.stringify(item.firstCommit)},`,
        `    lastCommit: ${JSON.stringify(item.lastCommit)},`,
        '  },',
      ].join('\n'),
    )
    .join('\n');

  return `// @generated by scripts/build-contributors.ts — DO NOT EDIT
// 贡献者数量：${contributors.length}

import type { Contributor } from '@/types/contributor';

export const CONTRIBUTORS: Contributor[] = [
${body}
];
`;
}

function main() {
  const checkOnly = process.argv.slice(2).includes('--check');
  const contributors = collect();
  const content = render(contributors);

  if (checkOnly) {
    let previous = '';
    try {
      previous = readFileSync(OUTPUT, 'utf8');
    } catch {
      logger.error('生成文件不存在，请先执行 pnpm build:contributors');
      process.exit(1);
    }
    if (previous.trim() === content.trim()) {
      logger.success('贡献者统计与 git 历史一致，无需更新');
      return;
    }
    logger.error('贡献者统计已过期，请执行 pnpm build:contributors 后提交');
    process.exit(1);
  }

  writeFileSync(OUTPUT, content, 'utf8');

  const totalCommits = contributors.reduce((sum, item) => sum + item.commits, 0);
  logger.summary(`已写入 ${OUTPUT.replace(ROOT, '.')}`, {
    贡献者: contributors.length,
    提交总数: totalCommits,
    数据贡献者: contributors.filter((item) => item.dataCommits > 0).length,
  });
}

main();
