/**
 * 生成客户端搜索索引（src/data/search-index.generated.ts）。
 *
 * 只写入检索必需的最小字段，避免 300+ 条完整数据进入首屏 JS。
 */
import { writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

import { getAllSites } from '../src/lib/sites';
import type { SearchDoc } from '../src/types/site';
import { logger } from './utils/log';

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const OUTPUT = resolve(ROOT, 'src/data/search-index.generated.ts');

function main() {
  const docs: SearchDoc[] = getAllSites().map((site) => ({
    id: site.id,
    name: site.name,
    nameCn: site.nameCn,
    category: site.category,
    tags: site.tags,
    description: site.description,
  }));

  const body = docs
    .map((doc) => {
      const parts = [
        `id: ${JSON.stringify(doc.id)}`,
        `name: ${JSON.stringify(doc.name)}`,
        doc.nameCn ? `nameCn: ${JSON.stringify(doc.nameCn)}` : null,
        `category: ${JSON.stringify(doc.category)}`,
        `tags: ${JSON.stringify(doc.tags)}`,
        `description: ${JSON.stringify(doc.description)}`,
      ].filter(Boolean);
      return `  { ${parts.join(', ')} },`;
    })
    .join('\n');

  const content = `// @generated by scripts/build-search-index.ts — DO NOT EDIT

import type { SearchDoc } from '@/types/site';

export const SEARCH_INDEX: SearchDoc[] = [
${body}
];
`;

  writeFileSync(OUTPUT, content, 'utf8');
  logger.summary(`已写入 ${OUTPUT.replace(ROOT, '.')}`, {
    索引条目: docs.length,
    估算体积: `${(content.length / 1024).toFixed(1)} KB`,
  });
}

main();
