/**
 * 官网图标抓取脚本（M5 · 自主收录管线）
 *
 * 收录不在 @lobehub/icons 图标库中的工具时，图标从官网抓取：
 * 优先 HTML 里声明的 `rel="icon"` / `apple-touch-icon`，兜底 `/favicon.ico`，
 * 落地到 `public/icons/<id>.<ext>`，并生成 `src/data/favicons.generated.ts`。
 *
 * 特性：增量（已存在则跳过）、并发受限、单次超时不阻塞整体、幂等可校验。
 *
 * 用法：
 *   pnpm fetch:favicons            # 增量抓取缺失图标
 *   pnpm fetch:favicons --force    # 强制重新抓取全部
 *   pnpm fetch:favicons --check    # 校验生成文件与 public/icons 是否一致（CI 门禁）
 */
import {
  existsSync,
  mkdirSync,
  readFileSync,
  readdirSync,
  unlinkSync,
  writeFileSync,
} from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

import { CATALOG_ENTRIES } from '../src/data/registry';
import { logger } from './utils/log';

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const ICON_DIR = resolve(ROOT, 'public/icons');
const OUTPUT = resolve(ROOT, 'src/data/favicons.generated.ts');

const CONCURRENCY = 8;
const TIMEOUT_MS = 8000;
const MAX_BYTES = 512 * 1024;
const USER_AGENT =
  'Mozilla/5.0 (compatible; awesome-ai-tools-favicon-bot/1.0; +https://github.com/Jlnvv-tom/awesome-ai-tools)';

interface Downloaded {
  buffer: Buffer;
  contentType: string | null;
}

/** 抓取单个 URL，失败返回 null（不抛出，避免单点失败中断整批） */
async function request(url: string, accept: string): Promise<Downloaded | null> {
  try {
    const response = await fetch(url, {
      redirect: 'follow',
      signal: AbortSignal.timeout(TIMEOUT_MS),
      headers: { 'user-agent': USER_AGENT, accept },
    });
    if (!response.ok) return null;

    const contentType = response.headers.get('content-type');
    const buffer = Buffer.from(await response.arrayBuffer());
    if (buffer.byteLength === 0 || buffer.byteLength > MAX_BYTES) return null;
    if (contentType?.includes('html') && !accept.includes('text/html')) return null;

    return { buffer, contentType };
  } catch (error) {
    console.error(`[favicons] 请求失败 ${url}：${(error as Error).message}`);
    return null;
  }
}

function extFromContentType(contentType: string | null): string | null {
  if (!contentType) return null;
  if (contentType.includes('svg')) return 'svg';
  if (contentType.includes('png')) return 'png';
  if (contentType.includes('webp')) return 'webp';
  if (contentType.includes('jpeg') || contentType.includes('jpg')) return 'jpg';
  if (contentType.includes('icon')) return 'ico';
  return null;
}

function extFromUrl(url: string): string | null {
  const matched = /\.(svg|png|webp|jpe?g|ico)(?:[?#]|$)/i.exec(url);
  if (!matched) return null;
  return matched[1].toLowerCase() === 'jpeg' ? 'jpg' : matched[1].toLowerCase();
}

/** 从 HTML 中解析图标地址：apple-touch-icon 优先（分辨率更高质量更好），其次 svg，最后其它 */
function extractIconHrefs(html: string, base: string): string[] {
  const hrefs: string[] = [];

  for (const match of html.matchAll(/<link\b[^>]*>/gi)) {
    const tag = match[0];
    if (!/rel\s*=\s*["']?[^"'>]*icon/i.test(tag)) continue;
    const href = /href\s*=\s*["']([^"']+)["']/i.exec(tag)?.[1];
    if (!href) continue;
    try {
      hrefs.push(new URL(href, base).toString());
    } catch (error) {
      console.error(`[favicons] 忽略非法图标地址：${href}`, (error as Error).message);
    }
  }

  const score = (url: string) => (/apple-touch-icon/i.test(url) ? 0 : /\.svg/i.test(url) ? 1 : 2);

  return [...new Set(hrefs)].sort((a, b) => score(a) - score(b));
}

/** 抓取单个条目：返回图标字节与扩展名 */
async function fetchIcon(url: string): Promise<{ buffer: Buffer; ext: string } | null> {
  const page = await request(url, 'text/html,application/xhtml+xml');

  if (page) {
    for (const href of extractIconHrefs(page.buffer.toString('utf8'), url)) {
      const icon = await request(href, 'image/*,*/*');
      if (!icon) continue;
      const ext = extFromContentType(icon.contentType) ?? extFromUrl(href) ?? 'png';
      return { buffer: icon.buffer, ext };
    }
  }

  const origin = new URL(url).origin;
  const fallback = await request(`${origin}/favicon.ico`, 'image/*,*/*');
  if (!fallback) return null;
  return {
    buffer: fallback.buffer,
    ext: extFromContentType(fallback.contentType) ?? 'ico',
  };
}

/** 读取 public/icons 下已有的图标：id → 文件名 */
function readLocalIcons(): Record<string, string> {
  if (!existsSync(ICON_DIR)) return {};
  const files: Record<string, string> = {};
  for (const file of readdirSync(ICON_DIR).sort()) {
    if (file.startsWith('.')) continue;
    const id = file.replace(/\.[^.]+$/, '');
    files[id] = file;
  }
  return files;
}

/** 生成映射文件内容（按 id 排序，保证幂等） */
function renderGenerated(files: Record<string, string>): string {
  const entries = Object.keys(files)
    .sort()
    .map((id) => `  ${JSON.stringify(id)}: ${JSON.stringify(`/icons/${files[id]}`)},`)
    .join('\n');

  const body = entries.length > 0 ? `{\n${entries}\n}` : '{}';

  return `// @generated by scripts/fetch-favicons.ts — DO NOT EDIT
// 记录已在 public/icons/ 落地的本地图标；值为 public 下的相对路径。
// 维护方式：pnpm fetch:favicons（增量抓取缺失项），CI 用 pnpm fetch:favicons --check 校验。

/** 条目 id → 本地图标路径（可能为 .png / .ico / .svg / .webp） */
export const FAVICON_FILES: Record<string, string> = ${body};
`;
}

/** 并发执行，保持结果顺序 */
async function mapLimit<T, R>(items: T[], limit: number, task: (item: T) => Promise<R>) {
  const results: R[] = new Array(items.length);
  let cursor = 0;

  const workers = Array.from({ length: Math.min(limit, items.length) }, async () => {
    while (cursor < items.length) {
      const index = cursor;
      cursor += 1;
      results[index] = await task(items[index]);
    }
  });

  await Promise.all(workers);
  return results;
}

function check(): void {
  const local = readLocalIcons();
  const expected: Record<string, string> = {};
  for (const entry of CATALOG_ENTRIES) {
    if (local[entry.id]) expected[entry.id] = local[entry.id];
  }

  const current = renderGenerated(local);
  const actual = existsSync(OUTPUT) ? readFileSync(OUTPUT, 'utf8') : '';

  if (current !== actual) {
    logger.error('本地图标映射与 public/icons 不一致，请执行 pnpm fetch:favicons 后提交');
    process.exit(1);
  }

  const untracked = Object.keys(local).filter((id) => !CATALOG_ENTRIES.some((e) => e.id === id));
  if (untracked.length > 0) {
    logger.warn(`${untracked.length} 个本地图标没有对应的 catalog 条目：${untracked.join(', ')}`);
  }

  logger.success(`本地图标映射一致（${Object.keys(expected).length} 个条目已有图标）`);
}

async function main() {
  const args = process.argv.slice(2);
  const force = args.includes('--force');

  if (args.includes('--check')) {
    check();
    return;
  }

  mkdirSync(ICON_DIR, { recursive: true });

  // 已有 iconId 的条目复用图标库，不需要本地图标
  const targets = CATALOG_ENTRIES.filter((entry) => !entry.iconId && entry.visible !== false);
  const existing = readLocalIcons();
  const hasLocalIcon = (id: string) => {
    const fileName = existing[id];
    return Boolean(fileName) && existsSync(resolve(ICON_DIR, fileName));
  };
  const pending = force ? targets : targets.filter((entry) => !hasLocalIcon(entry.id));

  logger.info(`待抓取 ${pending.length} 个条目（已有 ${targets.length - pending.length} 个）`);

  const outcomes = await mapLimit(pending, CONCURRENCY, async (entry) => {
    const icon = await fetchIcon(entry.url);
    if (!icon) return { entry, fileName: null as string | null };

    const fileName = `${entry.id}.${icon.ext}`;
    writeFileSync(resolve(ICON_DIR, fileName), icon.buffer);
    return { entry, fileName };
  });

  const succeeded = outcomes.filter((item) => item.fileName !== null);
  const failed = outcomes.filter((item) => item.fileName === null);

  // 强制模式下清理旧的同 id 其它扩展名文件，避免一个 id 存在多份图标
  if (force) {
    for (const entry of targets) {
      for (const file of readdirSync(ICON_DIR)) {
        if (file.startsWith(`${entry.id}.`) && !succeeded.some((s) => s.fileName === file)) {
          unlinkSync(resolve(ICON_DIR, file));
        }
      }
    }
  }

  const files = readLocalIcons();
  writeFileSync(OUTPUT, renderGenerated(files), 'utf8');

  logger.summary('官网图标抓取完成', {
    抓取成功: succeeded.length,
    抓取失败: failed.length,
    本地图标总数: Object.keys(files).length,
    映射文件: OUTPUT.replace(ROOT, '.'),
  });

  for (const item of failed) {
    logger.warn(`未能抓取图标：${item.entry.id}（${item.entry.url}）`);
  }
  if (failed.length > 0) {
    logger.info('失败条目会保持首字母块兜底，可稍后重跑或由贡献者在 PR 中提供图标');
  }
}

main();
