/**
 * 客观指标同步（M5）
 *
 * 只同步「可公开验证」的客观数据：GitHub Star 数（数据源为 GitHub REST API）。
 * 不使用任何第三方流量估计或用户行为数据，符合项目「不做什么」的中立约束。
 *
 * 特性：并发受限（GitHub 限流友好）、单个失败保留旧值、可用 GITHUB_TOKEN 提高限额。
 *
 * 用法：
 *   pnpm sync:metrics                 # 同步所有配置了 github 字段的条目
 *   pnpm sync:metrics --check         # 仅校验生成文件结构（不发网络请求，CI 用）
 *   GITHUB_TOKEN=xxx pnpm sync:metrics  # 提高 API 限额（CI 环境）
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

import { METRICS_SYNCED_AT, STARS } from '../src/data/metrics.generated';
import { getAllSites } from '../src/lib/sites';
import { logger } from './utils/log';

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const OUTPUT = resolve(ROOT, 'src/data/metrics.generated.ts');

const CONCURRENCY = 4;
const TIMEOUT_MS = 8000;
const USER_AGENT = 'awesome-ai-tools-metrics-bot';

/** 生成文件内容（按 id 排序，保证幂等） */
function render(syncedAt: string, stars: Record<string, number>): string {
  const entries = Object.keys(stars)
    .sort()
    .map((id) => `  ${JSON.stringify(id)}: ${stars[id]},`)
    .join('\n');

  const body = entries.length > 0 ? `{\n${entries}\n}` : '{}';

  return `// @generated by scripts/sync-metrics.ts — DO NOT EDIT
// 客观公开指标：目前仅 GitHub Star 数。
// 约束：只使用可公开验证的客观数据，不使用任何第三方流量估计（见 docs/adr/0009）。

/** 指标抓取时间（ISO 8601；空字符串表示尚未同步） */
export const METRICS_SYNCED_AT = ${JSON.stringify(syncedAt)};

/** 站点 id → GitHub Star 数 */
export const STARS: Record<string, number> = ${body};
`;
}

/** 并发执行，保持结果顺序 */
async function mapLimit<T, R>(items: T[], limit: number, task: (item: T) => Promise<R>) {
  const results: R[] = new Array(items.length);
  let cursor = 0;

  const workers = Array.from({ length: Math.min(limit, items.length) }, async () => {
    while (cursor < items.length) {
      const index = cursor;
      cursor += 1;
      results[index] = await task(items[index]);
    }
  });

  await Promise.all(workers);
  return results;
}

/** 拉取单个仓库的 Star 数；失败返回 null 以保留旧值 */
async function fetchStars(repo: string, token?: string): Promise<number | null> {
  const headers: Record<string, string> = {
    accept: 'application/vnd.github+json',
    'user-agent': USER_AGENT,
  };
  if (token) headers.authorization = `Bearer ${token}`;

  try {
    const response = await fetch(`https://api.github.com/repos/${repo}`, {
      headers,
      signal: AbortSignal.timeout(TIMEOUT_MS),
    });

    if (!response.ok) {
      logger.warn(
        `GitHub API ${response.status}：${repo}${token ? '' : '（未配置 GITHUB_TOKEN，可能触发限流）'}`,
      );
      return null;
    }

    const data = (await response.json()) as { stargazers_count?: number };
    return typeof data.stargazers_count === 'number' ? data.stargazers_count : null;
  } catch (error) {
    logger.warn(`拉取失败 ${repo}：${(error as Error).message}`);
    return null;
  }
}

function check(): void {
  const siteIds = new Set(getAllSites().map((site) => site.id));
  const problems: string[] = [];

  for (const [id, value] of Object.entries(STARS)) {
    if (!siteIds.has(id)) problems.push(`指标条目不存在于站点集合：${id}`);
    if (!Number.isInteger(value) || value < 0) problems.push(`Star 数非法：${id} → ${value}`);
  }

  if (METRICS_SYNCED_AT && Number.isNaN(Date.parse(METRICS_SYNCED_AT))) {
    problems.push(`同步时间不是合法 ISO 时间：${METRICS_SYNCED_AT}`);
  }

  const expected = render(METRICS_SYNCED_AT, STARS);
  const actual = readFileSync(OUTPUT, 'utf8');
  if (expected !== actual) problems.push('生成文件格式不规范，请执行 pnpm sync:metrics 重新生成');

  if (problems.length > 0) {
    for (const problem of problems) logger.error(problem);
    process.exit(1);
  }

  logger.success(`指标文件结构正确（${Object.keys(STARS).length} 条 Star 数据）`);
}

async function main() {
  const args = process.argv.slice(2);

  if (args.includes('--check')) {
    check();
    return;
  }

  const token = process.env.GITHUB_TOKEN;
  if (!token) {
    logger.warn('未配置 GITHUB_TOKEN：GitHub API 限额为每小时 60 次，仓库较多时可能失败');
  }

  const targets = getAllSites().filter((site) => Boolean(site.github));
  if (targets.length === 0) {
    logger.info(
      '没有条目配置 github 字段，跳过同步（在 SiteOverride / CatalogEntry 中填写后重试）',
    );
    return;
  }

  logger.info(`开始同步 ${targets.length} 个仓库的 Star 数（并发 ${CONCURRENCY}）`);

  const stars: Record<string, number> = {};
  const results = await mapLimit(targets, CONCURRENCY, async (site) => ({
    site,
    stars: await fetchStars(site.github as string, token),
  }));

  let updated = 0;
  let kept = 0;

  for (const { site, stars: value } of results) {
    if (value === null) {
      // 失败时保留上一次的值，避免把已知数据抹掉
      if (typeof STARS[site.id] === 'number') {
        stars[site.id] = STARS[site.id];
        kept += 1;
      }
      continue;
    }
    stars[site.id] = value;
    updated += 1;
  }

  const syncedAt = updated > 0 ? new Date().toISOString() : METRICS_SYNCED_AT;
  writeFileSync(OUTPUT, render(syncedAt, stars), 'utf8');

  logger.summary('客观指标同步完成', {
    目标仓库: targets.length,
    更新成功: updated,
    保留旧值: kept,
    结果条目: Object.keys(stars).length,
  });
}

main();
