/**
 * 图标元数据同步脚本（生成 src/data/icons.generated.ts）
 *
 * 数据来源优先级：
 *   1. 上游仓库 master 分支的 src/toc.json（322 条，含官网 URL）—— 权威且最全
 *   2. 已安装依赖 @lobehub/icons 的 toc（离线兜底，条目略少）
 *
 * 用法：
 *   pnpm sync:icons                 # 自动：远程优先，失败回退本地
 *   pnpm sync:icons --source=local  # 强制使用本地依赖
 *   pnpm sync:icons --check         # 只检查差异，不写文件（CI 用）
 */
import { existsSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

import { IconMetaSchema } from '../src/data/schema';
import type { IconMeta, IconVariantFlags } from '../src/types/site';
import { logger } from './utils/log';
import { normalizeColor, normalizeGroup, normalizeParam, normalizeUrl } from './utils/normalize';

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const OUTPUT = resolve(ROOT, 'src/data/icons.generated.ts');

const REMOTE_SOURCES = [
  'https://raw.githubusercontent.com/lobehub/lobe-icons/master/src/toc.json',
  'https://cdn.jsdelivr.net/gh/lobehub/lobe-icons@master/src/toc.json',
];

const FETCH_TIMEOUT_MS = 15_000;

interface RawTocItem {
  id: string;
  title: string;
  fullTitle: string;
  color?: string;
  colorGradient?: string;
  group: string;
  desc?: string;
  docsUrl?: string;
  param: Partial<IconVariantFlags>;
}

async function fetchRemote(): Promise<RawTocItem[] | null> {
  for (const url of REMOTE_SOURCES) {
    try {
      const controller = new AbortController();
      const timer = setTimeout(() => controller.abort(), FETCH_TIMEOUT_MS);
      const response = await fetch(url, { signal: controller.signal });
      clearTimeout(timer);
      if (!response.ok) throw new Error(`HTTP ${response.status}`);
      const data = (await response.json()) as unknown;
      const list = Array.isArray(data) ? data : (data as { toc?: unknown }).toc;
      if (!Array.isArray(list) || list.length === 0) throw new Error('空数据');
      logger.success(`远程数据源就绪：${url}（${list.length} 条）`);
      return list as RawTocItem[];
    } catch (error) {
      logger.warn(`远程数据源不可用：${url}`, (error as Error).message);
    }
  }
  return null;
}

async function loadLocal(): Promise<RawTocItem[]> {
  const { toc } = await import('@lobehub/icons');
  logger.info('使用本地依赖 @lobehub/icons 作为兜底数据源');
  return toc as unknown as RawTocItem[];
}

function normalize(list: RawTocItem[]): IconMeta[] {
  const seen = new Set<string>();
  const result: IconMeta[] = [];
  let skipped = 0;

  for (const item of list) {
    if (!item?.id || seen.has(item.id)) continue;
    const url = normalizeUrl(item.desc);
    if (!url) {
      skipped += 1;
      logger.warn(`条目缺少可用官网地址，已跳过：${item.id}`);
      continue;
    }
    const meta = IconMetaSchema.parse({
      id: item.id,
      title: item.title || item.id,
      fullTitle: item.fullTitle || item.title || item.id,
      color: normalizeColor(item.color),
      group: normalizeGroup(item.group),
      url,
      docsUrl: item.docsUrl ?? item.id.toLowerCase(),
      param: normalizeParam(item.param),
    });
    seen.add(meta.id);
    result.push(meta);
  }

  if (skipped > 0) logger.warn(`共跳过 ${skipped} 个缺少官网地址的条目`);
  return result.sort((a, b) => a.id.localeCompare(b.id));
}

function readPreviousIds(): Set<string> {
  if (!existsSync(OUTPUT)) return new Set();
  const content = readFileSync(OUTPUT, 'utf8');
  return new Set([...content.matchAll(/^ {4}id: ["'](.+)["'],$/gm)].map((match) => match[1]));
}

function renderFile(list: IconMeta[], source: string): string {
  const body = list
    .map((item) => {
      const param = Object.entries(item.param)
        .map(([key, value]) => `${key}: ${value}`)
        .join(', ');
      return [
        '  {',
        `    id: ${JSON.stringify(item.id)},`,
        `    title: ${JSON.stringify(item.title)},`,
        `    fullTitle: ${JSON.stringify(item.fullTitle)},`,
        `    color: ${JSON.stringify(item.color)},`,
        `    group: ${JSON.stringify(item.group)},`,
        `    url: ${JSON.stringify(item.url)},`,
        `    docsUrl: ${JSON.stringify(item.docsUrl)},`,
        `    param: { ${param} },`,
        '  },',
      ].join('\n');
    })
    .join('\n');

  return `// @generated by scripts/sync-icons.ts — DO NOT EDIT
// 数据来源：${source}
// 同步时间：${new Date().toISOString()}
// 条目数量：${list.length}

import type { IconMeta } from '@/types/site';

export const ICON_SOURCE = ${JSON.stringify(source)};

export const ICON_SYNCED_AT = ${JSON.stringify(new Date().toISOString())};

export const ICON_META: IconMeta[] = [
${body}
];
`;
}

async function main() {
  const args = process.argv.slice(2);
  const forceLocal = args.includes('--source=local');
  const checkOnly = args.includes('--check');

  const remote = forceLocal ? null : await fetchRemote();
  const raw = remote ?? (await loadLocal());
  const source = remote ? REMOTE_SOURCES[0] : '@lobehub/icons (local)';

  const list = normalize(raw);
  if (list.length === 0) {
    logger.error('未获取到任何图标元数据，已中止（保留原有生成文件）');
    process.exit(1);
  }

  const previous = readPreviousIds();
  const current = new Set(list.map((item) => item.id));
  const added = [...current].filter((id) => !previous.has(id));
  const removed = [...previous].filter((id) => !current.has(id));

  const groups = list.reduce<Record<string, number>>((acc, item) => {
    acc[item.group] = (acc[item.group] ?? 0) + 1;
    return acc;
  }, {});

  if (checkOnly) {
    if (added.length === 0 && removed.length === 0) {
      logger.success('图标元数据与上游一致，无需更新');
      return;
    }
    logger.warn('图标元数据存在差异', { added, removed });
    process.exit(1);
  }

  writeFileSync(OUTPUT, renderFile(list, source), 'utf8');

  logger.summary(`已写入 ${OUTPUT.replace(ROOT, '.')}`, {
    数据源: source,
    条目总数: list.length,
    新增: added.length,
    移除: removed.length,
    模型: groups.model ?? 0,
    服务商: groups.provider ?? 0,
    应用: groups.application ?? 0,
  });

  if (added.length > 0) logger.info(`新增图标：${added.slice(0, 20).join(', ')}`);
  if (removed.length > 0) logger.warn(`已移除图标：${removed.slice(0, 20).join(', ')}`);
}

main().catch((error) => {
  logger.error('同步图标失败', error);
  process.exit(1);
});
