// @generated by scripts/build-contributors.ts — DO NOT EDIT
// 贡献者数量：1

import type { Contributor } from '@/types/contributor';

export const CONTRIBUTORS: Contributor[] = [
  {
    name: "吴集焕",
    commits: 5,
    dataCommits: 3,
    firstCommit: "2026-09-08",
    lastCommit: "2026-09-11",
  },
];
