// @generated by scripts/fetch-favicons.ts — DO NOT EDIT
// 记录已在 public/icons/ 落地的本地图标；值为 public 下的相对路径。
// 维护方式：pnpm fetch:favicons（增量抓取缺失项），CI 用 pnpm fetch:favicons --check 校验。

/** 条目 id → 本地图标路径（可能为 .png / .ico / .svg / .webp） */
export const FAVICON_FILES: Record<string, string> = {
  "aippt": "/icons/aippt.ico",
  "bohrium": "/icons/bohrium.png",
  "gaoding-ai": "/icons/gaoding-ai.ico",
  "ibiling": "/icons/ibiling.ico",
  "liblibai": "/icons/liblibai.ico",
  "metaso": "/icons/metaso.png",
  "miaoda": "/icons/miaoda.png",
  "nanoai": "/icons/nanoai.svg",
  "napkin": "/icons/napkin.png",
  "wawawriter": "/icons/wawawriter.ico",
  "wenxiaobai": "/icons/wenxiaobai.png",
  "xfyun-zhiwen": "/icons/xfyun-zhiwen.png",
  "xiaohuanxiong": "/icons/xiaohuanxiong.svg",
};
