// @generated by scripts/sync-metrics.ts — DO NOT EDIT
// 客观公开指标：目前仅 GitHub Star 数。
// 约束：只使用可公开验证的客观数据，不使用任何第三方流量估计（见 docs/adr/0009）。

/** 指标抓取时间（ISO 8601；空字符串表示尚未同步） */
export const METRICS_SYNCED_AT = "2026-09-12T09:11:51.653Z";

/** 站点 id → GitHub Star 数 */
export const STARS: Record<string, number> = {
  "cherrystudio": 51712,
  "langfuse": 34498,
  "ollama": 180718,
  "openwebui": 151716,
  "unsloth": 76053,
  "vllm": 91548,
};
